### ISSUE TITLE
Is this code correct?

### ISSUE THREAD

**Issue by sebstepien** [EngincanV/Asp.Net-Core-Consul-Demo#1]
The helper class ConsulKeyValueProvider.cs contains new ConsulClient to instantiate the consul client, then all that DI startup code is not required. Shouldn't the helper class be getting its instance from DI?

**Comment by EngincanV** [comment]
@as1s, yes you are right. It is meaningless to register services to DI container if I'm going to move forward with a static helper class. I didn't realize it because I just wanted to demonstrate a simple sample. I'll make the necessary changes.

Thanks.
